### ISSUE TITLE
(All?) Links in Copilot VSCode extension page broken, and this repository read me?

### ISSUE THREAD

**Issue by HerbM** [Akshit6828/copilot-preview#1]
### Is this the real Copilot repository?
If not, do you know how or where to post issues/questions with a working link?

(All?) Links in Copilot VSCode extension page broken except sign up which shows the "waitlist" option and no way to signup or get to Discussions etc., 

This repository's (Akshit6828/copilot-preview) readme page also has the same/similar bad links that lead to pages with center pain "404" not found errors?

Apologies is this is unrelated.  Only thing I've found that might work and that is still valid.

**Comment by Akshit6828** [comment]
> Is this the real Copilot repository?

Hi @HerbM. **No,** this is not the real copilot repository. Actually, it's a cloned repo uploaded by me for improving some documentation.

> If not, do you know how or where to post issues/questions with a working link?


**The Actual Github Copilot is a private repository that can only be accessed by authorized users.**

> (All?) Links in Copilot VSCode extension page broken except sign up which shows the "waitlist" option and no way to signup or get to Discussions etc.,

Yes, actually you need to sign up for the waiting list and then the Github Team will review and give you access to Github Copilot Repository which is private. Only then only you can add to the discussion forum.


If you have any further doubts, please let me know. 😄

**Comment by HerbM** [comment]
Sorry to have bothered you.

I am and have been signed up.  Trying to figure out how to report problems.
